### ISSUE TITLE
Images don't have fixed attributes

### ISSUE THREAD

**Issue by chrzrdx** [kvsrinivas91/edyst-s19-choose-a-pokemon#2]
https://github.com/kvsrinivas91/edyst-s19-choose-a-pokemon/blob/bdcc43164fefbe90753300827e521adf0db91849/frontend/index.html#L64

Sometimes, you add height: 100px, while other times it is width:25%

Please standardize the image dimensions.

**Comment by kvsrinivas91** [comment]
Size of the images are standardized.
