### ISSUE TITLE
Why are you clearing floats here?

### ISSUE THREAD

**Issue by chrzrdx** [kvsrinivas91/edyst-s19-choose-a-pokemon#3]
https://github.com/kvsrinivas91/edyst-s19-choose-a-pokemon/blob/bdcc43164fefbe90753300827e521adf0db91849/frontend/index.html#L24

Just leave a comment explaining why you're clearing floats. If you're using code from the internet, make sure you leave the link of the website there as well. :)

**Comment by kvsrinivas91** [comment]
In order to make responsive cards I copied some of the code from the below link.
https://www.w3schools.com/howto/howto_css_column_cards.asp
