### ISSUE TITLE
Add a comment here explaining what :after means

### ISSUE THREAD

**Issue by chrzrdx** [kvsrinivas91/edyst-s19-choose-a-pokemon#6]
https://github.com/kvsrinivas91/edyst-s19-choose-a-pokemon/blob/74ca3d34b019d4ec30ed8f48bb1b707eee8b0f5c/frontend/index.html#L33

**Comment by kvsrinivas91** [comment]
Sir,
I am facing some problems with css , there are somethings which I have to learn, So for some part of the CSS code I am referring to other codes.
